---
swagger: '2.0'
info:
  description: "This REST-based API aims to leverage the tools of the <a href=\"https://github.com/GIScience/oshdb\"
    target=\"_blank\">OSHDB</a> through allowing to access some of its functionalities
    via HTTP requests. \nThe official documentation can be found <a href=\"https://docs.ohsome.org/ohsome-api/stable\"
    target=\"_blank\">here</a>. "
  version: 1.2.3
  title: ohsome API
  contact:
    name: Heidelberg Institute for Geoinformation Technology
    url: https://www.heigit.org
    email: info@heigit.org
  license:
    name: License of the used data
    url: https://ohsome.org/copyrights
host: localhost:8083
schemes:
  - http
basePath: "/v1"
tags:
  - name: Area
    description: Compute the area of polygonal OSM elements
  - name: Count
    description: Compute the count of point/linear/polygonal OSM elements
  - name: Length
    description: Compute the length of linear OSM elements
  - name: Perimeter
    description: Compute the perimeter of polygonal OSM elements
  - name: Users
    description: Compute data aggregation functions on users
paths:
  "/elements/area":
    get:
      tags:
        - Area
      summary: Area of OSM elements
      operationId: area
      produces:
        - application/json
        - text/csv
      parameters:
        - name: bboxes
          in: query
          description: 'WGS84 coordinates in the following format: id1:lon1,lat1,lon2,lat2|id2:lon1,lat1,lon2,lat2|...
          OR lon1,lat1,lon2,lat2|lon1,lat1,lon2,lat2|...; no default value (one boundary
          parameter must be defined)'
          required: false
          type: string
        #  default: 8.625,49.3711,8.7334,49.4397
        - name: bcircles
          in: query
          description: 'WGS84 coordinates + radius in meter in the following format:
          id1:lon,lat,r|id2:lon,lat,r|... OR lon,lat,r|lon,lat,r|...; no default value
          (one boundary parameter must be defined)'
          required: false
          type: string
        - name: bpolys
          in: query
          description: WGS84 coordinates given as a list of coordinate pairs (as for
            bboxes) or GeoJSON FeatureCollection. The first point has to be the same
            as the last point and MultiPolygons are only supported in GeoJSON; no default
            value (one boundary parameter must be defined)
          required: false
          type: string
        - name: filter
          in: query
          description: Combines several attributive filters, e.g. OSM type, the geometry
            (simple feature) type, as well as the OSM tag; no default value
          required: false
          type: string
          default: type:way
        - name: format
          in: query
          description: 'Output format geojson (for /groupBy/boundary resources only),
          csv, or json; default: json'
          required: false
          type: string
          default: json
        - name: keys
          in: query
          description: This parameter has been deprecated since v1.0. We encourage you
            to use the new parameter 'filter' instead.
          required: false
          type: string
        - name: showMetadata
          in: query
          description: 'Boolean operator ''true'' or ''false''; default: ''false'''
          required: false
          type: string
        - name: time
          in: query
          description: 'ISO-8601 conform timestring(s); default: latest timestamp within
          dataset'
          required: false
          type: string
          default: 2014-01-01/2017-01-01/P1Y
        - name: timeout
          in: query
          description: Custom timeout in seconds; no default value
          required: true
          type: string
        - name: types
          in: query
          description: This parameter has been deprecated since v1.0. We encourage you
            to use the new parameter 'filter' instead.
          required: false
          type: string
        - name: values
          in: query
          description: This parameter has been deprecated since v1.0. We encourage you
            to use the new parameter 'filter' instead.
          required: false
          type: string
      x-dependencies:
        - OnlyOne(bboxes, bcircles, bpolys);
      responses:
        '200':
          description: OK
          schema:
            "$ref": "#/definitions/DefaultAggregationResponse"
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '405':
          description: Method not allowed
        '413':
          description: Payload too large
        '500':
          description: Internal server error
        '501':
          description: Not implemented
        '503':
          description: Service Unavailable
